name: map_diff
description: A dart package to compare two maps and return the differences between them.
version: 1.0.1
repository: https://github.com/devfelipereis/map_diff

environment:
  sdk: ^3.4.0

dependencies:
  collection: ^1.18.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
